#!/bin/sh
# Set up the layered test environment of the ibus macOS integration
# in a self-contained prefix, for the testing layers documented in
# README.macOS.md.
#
# The environment is idempotent: the existing base, engine and data
# are reused.  The panel component is always written directly with
# the resolved paths instead of being patched from an installed
# template, because the installed templates may already have the
# placeholders filled (the sed of an already filled template is a
# silent no-op, which once pointed the daemon at a stale panel).
#
# Usage: macos/test-env.sh <base-install-prefix> [panel-path]
#   <base-install-prefix>  the install prefix of the ibus base (the
#                          --prefix of macos/build-upstream.sh, e.g.
#                          /tmp/ibus-test-env/prefix); the default
#                          is /tmp/ibus-test-env/prefix
#   panel-path the macospanel binary of the build to test; the
#              default is taken from the ibus prefix of this source
#              tree at build-install/prefix
#
# After the setup, the script starts the ibus-daemon and prints the
# test commands of each layer; it leaves the daemon running.

set -e

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PREFIX="${1:-/tmp/ibus-test-env/prefix}"
PANEL="${2:-$ROOT/build-install/prefix/libexec/ibus-ui-macospanel}"
DATA_DIR="$PREFIX/share/rime-data"
LOG="${IBUS_TEST_LOG:-/tmp/ibus-test-env-daemon.log}"

# Guard against the historical layout confusion: a base installed
# one directory above the given prefix shadows the components.
if [ -x "$(dirname "$PREFIX")/bin/ibus-daemon" ] &&
   [ "$(dirname "$PREFIX")/bin/ibus-daemon" != "$PREFIX/bin/ibus-daemon" ]; then
    echo "Warning: another ibus base exists at $(dirname "$PREFIX");" \
         "remove it to avoid the component confusion." >&2
fi

[ -x "$PANEL" ] || {
    echo "Panel not found at $PANEL;" \
         "build the integration first (ninja -C build-install install)." >&2
    exit 1
}

# The upstream base with the meson recipe
if [ ! -x "$PREFIX/bin/ibus-daemon" ]; then
    "$ROOT/macos/build-upstream.sh" master "$PREFIX"
fi

# The Homebrew at-spi2-core provides atk.pc in the Cellar directory
# only (globs do not expand inside the quoted environment below).
ATK_PC_DIR=$(ls -d /opt/homebrew/Cellar/at-spi2-core/*/lib/pkgconfig 2>/dev/null |
        head -1)

# ibus-rime with the Homebrew librime
if [ ! -x "$PREFIX/libexec/ibus-rime/ibus-engine-rime" ]; then
    SRC="${TMPDIR:-/tmp}/ibus-rime-src"
    [ -d "$SRC" ] || git clone --depth 1 \
            https://github.com/rime/ibus-rime.git "$SRC"
    (cd "$SRC" && \
     [ -n "$ATK_PC_DIR" ] && \
     PKG_CONFIG_PATH="$ATK_PC_DIR:$PREFIX/lib/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}" \
     cmake -B build -DCMAKE_INSTALL_PREFIX="$PREFIX" \
            -DRIME_DATA_DIR="$DATA_DIR" >/dev/null && \
     cmake --build build >/dev/null && cmake --install build >/dev/null)
fi

# The rime data set: prelude, luna-pinyin (with pinyin.yaml) and the
# essay dictionary
mkdir -p "$DATA_DIR"
for repo in rime-prelude rime-luna-pinyin rime-essay; do
    SRC="${TMPDIR:-/tmp}/$repo"
    [ -d "$SRC" ] || git clone --depth 1 \
            "https://github.com/rime/$repo.git" "$SRC"
done
cp "${TMPDIR:-/tmp}/rime-prelude/"*.yaml "$DATA_DIR/"
cp "${TMPDIR:-/tmp}/rime-luna-pinyin/"luna_pinyin*.yaml \
        "${TMPDIR:-/tmp}/rime-luna-pinyin/pinyin.yaml" "$DATA_DIR/"
cp "${TMPDIR:-/tmp}/rime-essay/essay.txt" "$DATA_DIR/"
mkdir -p "$HOME/.config/ibus/rime"
if [ ! -f "$HOME/.config/ibus/rime/default.custom.yaml" ]; then
    cat > "$HOME/.config/ibus/rime/default.custom.yaml" <<'EOF'
patch:
  schema_list:
    - schema: luna_pinyin
EOF
fi

# The panel component, written directly with the resolved path
mkdir -p "$PREFIX/share/ibus/component"
cat > "$PREFIX/share/ibus/component/macospanel.xml" <<EOF
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by macos/test-env.sh -->
<component>
	<name>org.freedesktop.IBus.Panel</name>
	<description>macOS Panel Component</description>
	<exec>$PANEL</exec>
	<version>1.5.35</version>
	<author>Weixuan XIAO &lt;veyx.shaw@gmail.com&gt;</author>
	<license>GPL</license>
	<textdomain>ibus</textdomain>
</component>
EOF

# Stop the leftovers and start the daemon with the default address
# file, which the launchd bridge also reads.
pkill -f "$PREFIX/bin/ibus-daemon" 2>/dev/null || true
for p in ibus-engine-rime ibus-engine-simple ibus-memconf ibus-ui-macospanel; do
    pkill -f "$p" 2>/dev/null || true
done
sleep 1
rm -rf "$HOME/.config/ibus/bus"
export DBUS_SESSION_BUS_ADDRESS=$(mkdir -p /tmp/ibus-test-session && \
        dbus-daemon --session --fork --print-address=1 \
                --address=unix:tmpdir=/tmp/ibus-test-session)
# G_MESSAGES_DEBUG must not be "all": the daemon passes it to the
# component engine enumeration children, whose g_debug output goes to
# the stdout being parsed as the engine XML and breaks the parse.
# Filter by the IBUS log domain of the panel instead.
# The engines read their GSettings schemas (e.g. libpinyin); compile
# the schemas of the base if needed and point the engines at them.
if [ -d "$PREFIX/share/glib-2.0/schemas" ] &&
        [ ! -f "$PREFIX/share/glib-2.0/schemas/gschemas.compiled" ]; then
    glib-compile-schemas "$PREFIX/share/glib-2.0/schemas"
fi
if [ -f "$PREFIX/share/glib-2.0/schemas/gschemas.compiled" ]; then
    export GSETTINGS_SCHEMA_DIR="$PREFIX/share/glib-2.0/schemas"
fi
# IBUS_ENABLE_CTRL_SHIFT_U enables the hex compose sequence of the
# simple engine, which the hex compose round-trip test uses.
G_MESSAGES_DEBUG=IBUS IBUS_MACOSPANEL_VERTICAL=1 \
IBUS_ENABLE_CTRL_SHIFT_U=1 "$PREFIX/bin/ibus-daemon" --replace -v > "$LOG" 2>&1 &
sleep 5

echo "The daemon is running (log: $LOG, address file: default)."
echo "Verify the panel path before the tests:"
grep -o "<exec>[^<]*</exec>" "$PREFIX/share/ibus/component/macospanel.xml"
echo
echo "D-Bus layer:"
echo "  printf 'nihao\\n' | $ROOT/build-install/prefix/libexec/ibus-macos-client rime"
echo "XPC layer:"
echo "  $ROOT/build-install/prefix/libexec/ibus-xpc-test-client --keys rime nihao"
echo "Panel data flow:  grep -E 'focus in|lookup table' $LOG"
